import turtle

drawing_board = turtle.Screen()
drawing_board.bgcolor("orange")
drawing_board.title("Python Turtle")

turtle_instance = turtle.Turtle()
#turtle_instance.left(50)
#turtle_instance.forward(60)
#turtle_instance.right(90)
#turtle_instance.forward(60)
#turtle_instance.right(220)
#turtle_instance.forward(60)
#turtle_instance.right(50)
#turtle_instance.forward(60)
#turtle_instance.left(125)
#turtle_instance.forward(60)
#turtle_instance.right(60)
#turtle_instance.forward(60)
#turtle_instance.left(140)
#turtle_instance.forward(60)
#turtle_instance.right(60)
#turtle_instance.forward(60)
#turtle_instance.left(140)
#turtle_instance.forward(60)
#turtle_instance.right(75)
#turtle_instance.forward(75)
turtle.done()